"""Generate MQTT credentials + HiveMQ ACL + credentials.xml from the fleet.

Produces three artifacts in one pass so they cannot drift:

    secrets/mqtt_credentials.csv  — room_key,username,password  (100 rows)
    hivemq/conf/credentials.xml   — file-realm user entries
    hivemq/acl/acl.xml            — per-node roles + gateway + tb-integration

Also includes 10 gateway users (gateway-floor-NN) and one tb-integration
user so HiveMQ's file RBAC extension has the full set of principals.

Idempotent: re-running without FORCE=1 preserves existing passwords
from the CSV so running clients stay authenticated.

Usage:  venv/bin/python secrets/generate_mqtt_creds.py
"""

import csv
import os
import secrets
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.engine.fleet import create_room_fleet  # noqa: E402

CSV_PATH = Path(__file__).resolve().parent / "mqtt_credentials.csv"
CRED_XML = ROOT / "hivemq" / "conf" / "credentials.xml"
ACL_XML = ROOT / "hivemq" / "acl" / "acl.xml"
FORCE = os.getenv("FORCE") == "1"
NUM_FLOORS = 10


def _user_for_mqtt_room(room_key):
    return f"mqtt-node-{room_key}"


def _user_for_coap_room(room_key):
    return f"coap-node-{room_key}"


def _user_for_gateway(floor):
    return f"gateway-floor-{floor:02d}"


def _load_existing_csv():
    if not CSV_PATH.exists() or FORCE:
        return {}
    existing = {}
    with CSV_PATH.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            existing[row["room_key"]] = (row["username"], row["password"])
    return existing


def _build_credentials():
    fleet = create_room_fleet()
    existing = _load_existing_csv()
    entries = []

    # One username/password per room regardless of protocol — CoAP nodes
    # don't use MQTT auth themselves but the gateway may need a principal
    # when publishing their telemetry, and TB's registry is cleaner if
    # every room has a row.
    for room in fleet:
        key = room.room_key
        if key in existing:
            user, pw = existing[key]
        else:
            user = (
                _user_for_mqtt_room(key)
                if room.protocol == "mqtt"
                else _user_for_coap_room(key)
            )
            pw = secrets.token_urlsafe(16)
        entries.append(
            {
                "room_key": key,
                "username": user,
                "password": pw,
                "protocol": room.protocol,
                "floor_id": room.floor_id,
            }
        )
    return entries


def _write_csv(entries):
    with CSV_PATH.open("w", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["room_key", "username", "password", "protocol", "floor_id"]
        )
        writer.writeheader()
        for e in entries:
            writer.writerow(e)


def _write_hivemq_credentials(entries):
    CRED_XML.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by secrets/generate_mqtt_creds.py — do not edit by hand -->",
        "<file-rbac>",
        "  <users>",
    ]
    for e in entries:
        lines.append("    <user>")
        lines.append(f"      <name>{escape(e['username'])}</name>")
        lines.append(f"      <password>{escape(e['password'])}</password>")
        role = (
            f"mqtt-node-{e['room_key']}"
            if e["protocol"] == "mqtt"
            else f"coap-node-{e['room_key']}"
        )
        lines.append(f"      <roles><id>{escape(role)}</id></roles>")
        lines.append("    </user>")

    for floor in range(1, NUM_FLOORS + 1):
        gw_user = _user_for_gateway(floor)
        gw_pw = secrets.token_urlsafe(16)
        lines.append("    <user>")
        lines.append(f"      <name>{escape(gw_user)}</name>")
        lines.append(f"      <password>{escape(gw_pw)}</password>")
        lines.append(f"      <roles><id>{escape(gw_user)}</id></roles>")
        lines.append("    </user>")

    lines.append("    <user>")
    lines.append("      <name>tb-integration</name>")
    lines.append(f"      <password>{escape(secrets.token_urlsafe(24))}</password>")
    lines.append("      <roles><id>tb-integration</id></roles>")
    lines.append("    </user>")
    lines.append("  </users>")
    lines.append("</file-rbac>")

    CRED_XML.write_text("\n".join(lines) + "\n")


def _write_hivemq_acl(entries):
    ACL_XML.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by secrets/generate_mqtt_creds.py — do not edit by hand -->",
        "<file-rbac>",
        "  <roles>",
    ]

    for e in entries:
        if e["protocol"] != "mqtt":
            continue
        key = e["room_key"]
        role = f"mqtt-node-{key}"
        floor_id = e["floor_id"]
        # room_key already encodes the full room number (e.g. b01-f01-r101)
        room_number = int(key.split("-r")[1])
        base = f"campus/b01/f{floor_id:02d}/r{room_number:03d}"
        lines += [
            f'    <role><id>{escape(role)}</id><permissions>',
            f"      <permission><topic>{base}/#</topic><activity>PUBLISH</activity></permission>",
            f"      <permission><topic>{base}/cmd</topic><activity>SUBSCRIBE</activity></permission>",
            "    </permissions></role>",
        ]

    for floor in range(1, NUM_FLOORS + 1):
        role = _user_for_gateway(floor)
        base = f"campus/b01/f{floor:02d}"
        lines += [
            f'    <role><id>{escape(role)}</id><permissions>',
            f"      <permission><topic>{base}/#</topic><activity>PUBLISH</activity></permission>",
            f"      <permission><topic>{base}/#</topic><activity>SUBSCRIBE</activity></permission>",
            "    </permissions></role>",
        ]

    lines += [
        '    <role><id>tb-integration</id><permissions>',
        "      <permission><topic>campus/#</topic><activity>SUBSCRIBE</activity></permission>",
        "      <permission><topic>campus/+/+/+/cmd</topic><activity>PUBLISH</activity></permission>",
        "    </permissions></role>",
        "  </roles>",
        "</file-rbac>",
    ]

    ACL_XML.write_text("\n".join(lines) + "\n")


def main():
    entries = _build_credentials()
    _write_csv(entries)
    _write_hivemq_credentials(entries)
    _write_hivemq_acl(entries)
    print(
        f"wrote {CSV_PATH} ({len(entries)} rows), "
        f"{CRED_XML}, {ACL_XML}"
    )


if __name__ == "__main__":
    main()
